name: Test
on:
    pull_request:
    push:
        branches:
            - main
            - "releases/*"

jobs:
    # unit tests
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Install specific Yarn version
              run: npm i -g --force yarn@1.22.17
            - name: Copies .env variable
              run: cp .env.example .env
            - uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: install
            - uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: typechain
            - uses: borales/actions-yarn@v3.0.0
              with:
                  cmd: test
